# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190326_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
